-- Test Data for Threads Table
-- This SQL file inserts sample thread data for testing the forums/threads page

-- Insert test threads
INSERT INTO public.threads (
  title,
  slug,
  content,
  tags,
  author_name,
  author_email,
  is_approved,
  is_locked,
  like_count,
  view_count,
  is_featured,
  created_at,
  updated_at
) VALUES
(
  'Best Practices for Drug-Drug Interaction Screening',
  'best-practices-drug-drug-interaction-screening',
  'I''ve been working on a comprehensive drug-drug interaction screening protocol for our pharmacy. What are the most reliable databases and tools you all use? I''m particularly interested in real-world evidence and clinical decision support systems. Also, how do you handle interactions between herbal supplements and prescription medications?',
  ARRAY['pharmacy', 'drug-interactions', 'clinical-practice', 'safety'],
  'Dr. Sarah Chen',
  'sarah.chen@example.com',
  true,
  false,
  24,
  156,
  true,
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '5 days'
),
(
  'Pharmacogenomics in Clinical Practice: Case Studies',
  'pharmacogenomics-clinical-practice-case-studies',
  'I recently had a patient who was a poor metabolizer for CYP2D6, and we had to adjust their codeine prescription. I''d love to hear about other real-world cases where pharmacogenomic testing directly influenced treatment decisions. What testing platforms do you recommend?',
  ARRAY['pharmacogenomics', 'personalized-medicine', 'case-study', 'genetics'],
  'Dr. Michael Rodriguez',
  'm.rodriguez@example.com',
  true,
  false,
  18,
  203,
  true,
  NOW() - INTERVAL '8 days',
  NOW() - INTERVAL '8 days'
),
(
  'Antibiotic Stewardship: Balancing Efficacy and Resistance',
  'antibiotic-stewardship-balancing-efficacy-resistance',
  'With the rise of antimicrobial resistance, how are you implementing antibiotic stewardship programs in your practice? I''m looking for strategies that maintain patient outcomes while reducing unnecessary antibiotic use. What metrics do you track?',
  ARRAY['antibiotics', 'antimicrobial-resistance', 'stewardship', 'infectious-disease'],
  'Dr. Emily Watson',
  'emily.watson@example.com',
  true,
  false,
  31,
  289,
  false,
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '3 days'
),
(
  'Managing Opioid Prescriptions: New Guidelines Discussion',
  'managing-opioid-prescriptions-new-guidelines',
  'The CDC recently updated their opioid prescribing guidelines. How are these changes affecting your practice? I''m particularly concerned about patients with chronic pain who have been stable on long-term opioid therapy. What''s your approach to tapering and alternative pain management?',
  ARRAY['opioids', 'pain-management', 'guidelines', 'chronic-pain'],
  'Dr. James Park',
  'j.park@example.com',
  true,
  false,
  15,
  178,
  false,
  NOW() - INTERVAL '12 days',
  NOW() - INTERVAL '12 days'
),
(
  'Biosimilars vs. Biologics: Clinical Equivalence Evidence',
  'biosimilars-vs-biologics-clinical-equivalence',
  'We''re seeing more biosimilar approvals, but there''s still hesitancy in switching patients from originator biologics. What clinical evidence do you need to see before making the switch? Have you encountered any issues with interchangeability?',
  ARRAY['biosimilars', 'biologics', 'oncology', 'rheumatology'],
  'Dr. Lisa Thompson',
  'lisa.thompson@example.com',
  true,
  false,
  22,
  234,
  false,
  NOW() - INTERVAL '6 days',
  NOW() - INTERVAL '6 days'
),
(
  'Pediatric Dosing: Weight-Based vs. BSA Calculations',
  'pediatric-dosing-weight-based-vs-bsa-calculations',
  'When calculating pediatric doses, when do you use weight-based dosing versus body surface area (BSA)? I''ve seen inconsistencies in protocols, especially for chemotherapy and critical care medications. What''s your standard approach?',
  ARRAY['pediatrics', 'dosing', 'pharmacokinetics', 'pediatric-pharmacy'],
  'Dr. Robert Kim',
  'r.kim@example.com',
  true,
  false,
  19,
  167,
  false,
  NOW() - INTERVAL '10 days',
  NOW() - INTERVAL '10 days'
),
(
  'Medication Adherence: Technology and Patient Engagement',
  'medication-adherence-technology-patient-engagement',
  'What digital tools and strategies are you using to improve medication adherence? I''m interested in apps, smart pill dispensers, and patient education platforms. What has shown the most success in your patient population?',
  ARRAY['adherence', 'technology', 'patient-engagement', 'digital-health'],
  'Dr. Amanda Foster',
  'amanda.foster@example.com',
  true,
  false,
  27,
  312,
  true,
  NOW() - INTERVAL '4 days',
  NOW() - INTERVAL '4 days'
),
(
  'Compounding Pharmacy: Regulatory Updates and Best Practices',
  'compounding-pharmacy-regulatory-updates-best-practices',
  'With recent FDA guidance on compounding, how are you ensuring compliance? I''m particularly interested in sterile compounding standards and beyond-use dating. What quality control measures do you have in place?',
  ARRAY['compounding', 'regulatory', 'sterile-compounding', 'quality-control'],
  'Dr. David Martinez',
  'd.martinez@example.com',
  true,
  false,
  12,
  145,
  false,
  NOW() - INTERVAL '15 days',
  NOW() - INTERVAL '15 days'
),
(
  'Drug Shortages: Mitigation Strategies and Alternatives',
  'drug-shortages-mitigation-strategies-alternatives',
  'We''re experiencing shortages of several critical medications. How are you managing inventory and communicating with prescribers about alternatives? What''s your protocol for therapeutic substitutions during shortages?',
  ARRAY['drug-shortages', 'inventory-management', 'therapeutic-substitution', 'supply-chain'],
  'Dr. Jennifer Lee',
  'jennifer.lee@example.com',
  true,
  false,
  33,
  267,
  false,
  NOW() - INTERVAL '7 days',
  NOW() - INTERVAL '7 days'
),
(
  'Clinical Trials: Patient Recruitment and Retention',
  'clinical-trials-patient-recruitment-retention',
  'I''m coordinating a Phase III trial and struggling with patient recruitment. What strategies have worked for you? Also, how do you maintain patient engagement throughout long-term trials?',
  ARRAY['clinical-trials', 'research', 'patient-recruitment', 'trial-management'],
  'Dr. Christopher Brown',
  'c.brown@example.com',
  true,
  false,
  8,
  98,
  false,
  NOW() - INTERVAL '20 days',
  NOW() - INTERVAL '20 days'
),
(
  'Medication Errors: Root Cause Analysis and Prevention',
  'medication-errors-root-cause-analysis-prevention',
  'After a recent near-miss, we''re reviewing our medication error reporting system. What frameworks do you use for root cause analysis? How do you balance blame-free reporting with accountability?',
  ARRAY['medication-errors', 'patient-safety', 'quality-improvement', 'risk-management'],
  'Dr. Nicole Anderson',
  'nicole.anderson@example.com',
  true,
  false,
  21,
  189,
  false,
  NOW() - INTERVAL '9 days',
  NOW() - INTERVAL '9 days'
),
(
  'Geriatric Pharmacy: Polypharmacy and Deprescribing',
  'geriatric-pharmacy-polypharmacy-deprescribing',
  'Managing medications in elderly patients with multiple comorbidities is challenging. What''s your approach to deprescribing? How do you prioritize which medications to reduce or discontinue?',
  ARRAY['geriatrics', 'polypharmacy', 'deprescribing', 'elderly-care'],
  'Dr. Mark Wilson',
  'mark.wilson@example.com',
  true,
  false,
  16,
  223,
  false,
  NOW() - INTERVAL '11 days',
  NOW() - INTERVAL '11 days'
),
(
  'Oncology Pharmacy: CAR-T Cell Therapy Management',
  'oncology-pharmacy-car-t-cell-therapy-management',
  'We''re starting to see CAR-T cell therapy patients. What''s your protocol for managing cytokine release syndrome and other toxicities? How do you coordinate with the oncology team?',
  ARRAY['oncology', 'car-t-therapy', 'immunotherapy', 'cancer-treatment'],
  'Dr. Rachel Green',
  'rachel.green@example.com',
  true,
  false,
  29,
  278,
  true,
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '2 days'
),
(
  'Telepharmacy: Remote Patient Monitoring and Consultations',
  'telepharmacy-remote-patient-monitoring-consultations',
  'With the expansion of telepharmacy services, what technologies are you using for remote consultations? How do you ensure patient privacy and maintain the quality of care?',
  ARRAY['telepharmacy', 'telemedicine', 'remote-care', 'digital-pharmacy'],
  'Dr. Thomas White',
  'thomas.white@example.com',
  true,
  false,
  14,
  156,
  false,
  NOW() - INTERVAL '14 days',
  NOW() - INTERVAL '14 days'
),
(
  'Vaccine Storage and Handling: Cold Chain Management',
  'vaccine-storage-handling-cold-chain-management',
  'Proper vaccine storage is critical. What monitoring systems do you use? How do you handle temperature excursions? I''m looking for best practices for maintaining the cold chain.',
  ARRAY['vaccines', 'cold-chain', 'storage', 'immunization'],
  'Dr. Patricia Davis',
  'patricia.davis@example.com',
  true,
  false,
  11,
  134,
  false,
  NOW() - INTERVAL '18 days',
  NOW() - INTERVAL '18 days'
)
ON CONFLICT (slug) DO NOTHING;

-- Verify the insert
SELECT 
  id,
  title,
  slug,
  author_name,
  is_approved,
  is_featured,
  like_count,
  view_count,
  created_at
FROM public.threads
WHERE is_approved = true
ORDER BY created_at DESC;

